# Generated by Django 4.2.23 on 2025-08-06 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='custom_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='reminder',
            name='interval_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'One-time'), ('interval', 'Every X minutes'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_day', 'Specific day of the month'), ('custom_weekday', 'Specific weekdays')], default='none', max_length=20),
        ),
    ]
