# Generated by Django 4.2.23 on 2025-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reminder_custom_day_of_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='custom_day_of_month',
            new_name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='custom_weekdays',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='next_run',
        ),
        migrations.AddField(
            model_name='reminder',
            name='day_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'One-time'), ('interval', 'Repeat every X minutes'), ('custom_day', 'Monthly on specific day'), ('custom_weekday', 'Weekly on specific weekday')], default='none', max_length=20),
        ),
    ]
